/**
 * Universal Standard Error Types for the Fiber Route Map API.
 * These identifiers allow clients to programmatically handle different failure states.
 */
export const ErrorType = {
  // Client Errors (4xx)
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Authentication & Session Specifics
  SESSION_LIMIT_REACHED: 'SESSION_LIMIT_REACHED',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Server Errors (5xx)
  SERVER_ERROR: 'SERVER_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',
} as const;

export type ErrorType = typeof ErrorType[keyof typeof ErrorType];
