import 'dotenv/config';

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Auto-create .env if it doesn't exist so dotenv picks it up on next start
// and setup wizard has a writable target from day one.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.resolve(__dirname, '../.env');
if (!fs.existsSync(envPath)) {
  fs.writeFileSync(envPath, '# Fiber Route Map — generated by first-run\nSETUP_COMPLETE=false\n', 'utf-8');
}

import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { errorHandler } from './middleware/errorHandler.js';
import { versionCheck } from './middleware/versionCheck.js';
import { requestId } from './middleware/requestId.js';
import { dbCheck } from './middleware/dbCheck.js';
import { auth } from './middleware/auth.js';
import userRoutes from './routes/userRoutes.js';
import countryRoutes from './routes/countryRoutes.js';
import roleRoutes from './routes/roleRoutes.js';
import permissionRoutes from './routes/permissionRoutes.js';
import healthRoutes from './routes/healthRoutes.js';
import { authRoutes } from './routes/authRoutes.js';
import setupRoutes from './routes/setupRoutes.js';
import tenantRoutes from './routes/tenantRoutes.js';
import tenantBusinessRoutes from './routes/tenantBusinessRoutes.js';
import lcoRoutes from './routes/lcoRoutes.js';
import tenantUserRoutes from './routes/tenantUserRoutes.js';
import tenantUpstreamProviderRoutes from './routes/tenantUpstreamProviderRoutes.js';
import tenantCableTypeRoutes from './routes/tenantCableTypeRoutes.js';
import tenantDeviceCategoryRoutes from './routes/tenantDeviceCategoryRoutes.js';
import tenantDeviceTypeRoutes from './routes/tenantDeviceTypeRoutes.js';
import tenantUserSettingRoutes from './routes/tenantUserSettingRoutes.js';
import tenantSupportTicketRoutes from './routes/tenantSupportTicketRoutes.js';
import adminSupportTicketRoutes from './routes/adminSupportTicketRoutes.js';
import widgetRoutes from './routes/widgetRoutes.js';
import tenantRouteRoutes from './routes/tenantRouteRoutes.js';
import tenantWidgetRoutes from './routes/tenantWidgetRoutes.js';
import auditLogRoutes, { auditLogService } from './routes/auditLogRoutes.js';
import { auditLog } from './middleware/auditLog.js';
import logger from './utils/logger.js';
import db from './config/database.js';
import swaggerUi from 'swagger-ui-express';
import { swaggerSpec } from './docs/swaggerConfig.js';
import { AuthRepository } from './repositories/AuthRepository.js';
import { UserRepository } from './repositories/UserRepository.js';
import { TenantRepository } from './repositories/TenantRepository.js';
import { AuthService } from './services/AuthService.js';

const app = express();
const port = process.env.PORT || 3001;

// Initialize repositories and services
const authRepo = new AuthRepository();
const userRepo = new UserRepository();
const tenantRepo = new TenantRepository();
const authService = new AuthService(authRepo, userRepo, tenantRepo);

// Use extended query parser (qs) to support nested bracket notation like filter[status]=active
app.set('query parser', 'extended');

// Middleware
app.use(helmet());
app.use(cors({
  origin: '*', // For development, adjust for production
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH'],
  allowedHeaders: ['Content-Type', 'Authorization', 'X-API-Version', 'X-Mgmt-Token', 'X-Device-Id', 'X-Device-Name'],
  exposedHeaders: ['Content-Type', 'Authorization']
}));
app.use(express.json());
app.use(requestId);

// Setup routes — BEFORE versionCheck/dbCheck/auth so they work before DB exists
app.use('/api/setup', setupRoutes);

app.use(versionCheck);
app.use(dbCheck);

// Audit log middleware — runs on all API routes (after auth is available per-route)
app.use('/api', auditLog(auditLogService));

// Routes
app.use('/api/auth', authRoutes(authService));
app.use('/api/users', auth(authService), userRoutes);
app.use('/api/countries', auth(authService), countryRoutes);
app.use('/api/roles', auth(authService), roleRoutes);
app.use('/api/permissions', permissionRoutes);
app.use('/api/tenants', auth(authService), tenantRoutes);
app.use('/api/tenant-business', auth(authService), tenantBusinessRoutes);
app.use('/api/tenant/lcos', lcoRoutes);
app.use('/api/tenant/users', tenantUserRoutes);
app.use('/api/tenant/upstream-providers', tenantUpstreamProviderRoutes);
app.use('/api/tenant/cable-types', tenantCableTypeRoutes);
app.use('/api/tenant/device-categories', tenantDeviceCategoryRoutes);
app.use('/api/tenant/device-types', tenantDeviceTypeRoutes);
app.use('/api/tenant/user-settings', tenantUserSettingRoutes);
app.use('/api/tenant/support-tickets', tenantSupportTicketRoutes);
app.use('/api/support-tickets', auth(authService), adminSupportTicketRoutes);
app.use('/api/audit-logs', auth(authService), auditLogRoutes);
app.use('/api/widgets', auth(authService), widgetRoutes);
app.use('/api/tenant/routes', tenantRouteRoutes);
app.use('/api/tenant/widgets', tenantWidgetRoutes);
app.use('/api/health', healthRoutes);
app.get('/api/docs/spec', (_req: express.Request, res: express.Response) => res.json(swaggerSpec));
app.use('/api/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));

// Root route
app.get('/', (_req: express.Request, res: express.Response) => {
  res.json({ message: 'Fiber Route Map Node.js API' });
});

/*
// Catch-all for undefined /api routes
app.all('/api/:path*', (req: express.Request, res: express.Response) => {
  res.status(200).json({
    success: false,
    statusCode: 404,
    errorType: 'NOT_FOUND',
    message: `Route ${req.method} ${req.url} not found`,
    help: 'Please verify the API endpoint and HTTP method.'
  });
});
*/

// Error handling
app.use(errorHandler);

// Ensure audit_logs table exists (auto-migration for existing installs)
const ensureAuditLogsTable = async () => {
  try {
    const exists = await db.schema.hasTable('audit_logs');
    if (!exists) {
      await db.schema.createTable('audit_logs', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.enum('actorType', ['user', 'system', 'anonymous']).notNullable().defaultTo('anonymous');
        t.string('actorUuid', 36).nullable();
        t.string('actorName', 255).nullable();
        t.string('actorEmail', 191).nullable();
        t.json('actorRoles').nullable();
        t.string('action', 100).notNullable();
        t.string('resource', 100).notNullable();
        t.string('resourceUuid', 36).nullable();
        t.string('resourceName', 255).nullable();
        t.string('httpMethod', 10).notNullable();
        t.string('endpoint', 500).notNullable();
        t.smallint('statusCode').unsigned().notNullable();
        t.boolean('success').notNullable().defaultTo(true);
        t.json('requestBody').nullable();
        t.json('responseBody').nullable();
        t.string('ipAddress', 45).nullable();
        t.text('userAgent').nullable();
        t.string('requestId', 100).nullable();
        t.string('sessionUuid', 36).nullable();
        t.integer('durationMs').unsigned().notNullable().defaultTo(0);
        t.text('errorMessage').nullable();
        t.timestamp('createdAt').notNullable().defaultTo(db.fn.now());
        t.index(['actorUuid'], 'idx_audit_actor_uuid');
        t.index(['action'], 'idx_audit_action');
        t.index(['resource'], 'idx_audit_resource');
        t.index(['createdAt'], 'idx_audit_created');
        t.index(['statusCode'], 'idx_audit_status_code');
        t.index(['ipAddress'], 'idx_audit_ip');
        t.index(['requestId'], 'idx_audit_request_id');
      });
      logger.info('Auto-migration: audit_logs table created');

      // Seed audit_log permissions if the permissions table exists
      const hasPermissions = await db.schema.hasTable('permissions');
      if (hasPermissions) {
        const { generateUuidV7 } = await import('./utils/uuid.js');
        const { nowDb } = await import('./utils/time.js');
        const now = nowDb();
        for (const action of ['view', 'export']) {
          const slug = `audit_log.${action}`;
          const existing = await db('permissions').where('slug', slug).first();
          if (!existing) {
            await db('permissions').insert({
              uuid: generateUuidV7(),
              name: `${action.charAt(0).toUpperCase() + action.slice(1)} Audit Logs`,
              slug,
              resource: 'audit_log',
              description: `Can ${action} audit logs`,
              createdAt: now,
              updatedAt: now,
            });
            logger.info(`Auto-migration: seeded permission '${slug}'`);
          }
        }

        // Assign new permissions to Super Admin role if it exists
        const superAdminRole = await db('roles').where('slug', 'super-admin').select('id').first();
        if (superAdminRole) {
          const newPerms = await db('permissions')
            .whereIn('slug', ['audit_log.view', 'audit_log.export'])
            .select('id');
          for (const perm of newPerms) {
            await db.raw(
              'INSERT IGNORE INTO role_permissions (roleId, permissionId) VALUES (?, ?)',
              [superAdminRole.id, perm.id]
            );
          }
          logger.info('Auto-migration: audit_log permissions assigned to Super Admin role');
        }
      }
    }
  } catch (err: any) {
    logger.warn('Auto-migration for audit_logs skipped or failed', { error: err.message });
  }
};

// Ensure tenant_sessions table exists (auto-migration for existing installs using tenant_refresh_tokens)
const ensureTenantSessionsTable = async () => {
  try {
    const exists = await db.schema.hasTable('tenant_sessions');
    if (!exists) {
      await db.schema.createTable('tenant_sessions', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.integer('tenantId').unsigned().notNullable();
        t.string('sessionToken', 500).notNullable().unique();
        t.string('deviceId', 255).nullable();
        t.string('deviceName', 255).nullable();
        t.string('ipAddress', 45).nullable();
        t.text('userAgent').nullable();
        t.datetime('expiresAt').notNullable();
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.index(['tenantId'], 'idx_tenant_sessions_tenant_id');
        t.index(['expiresAt'], 'idx_tenant_sessions_expires_at');
      });
      logger.info('Auto-migration: tenant_sessions table created');
    }
  } catch (err: any) {
    logger.warn('Auto-migration for tenant_sessions skipped or failed', { error: err.message });
  }
};

// Ensure tenant_users table exists (auto-migration for v1.39.0)
const ensureTenantUsersTable = async () => {
  try {
    const exists = await db.schema.hasTable('tenant_users');
    if (!exists) {
      await db.schema.createTable('tenant_users', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.integer('tenantId').unsigned().notNullable();
        t.string('name', 255).notNullable();
        t.string('username', 100).notNullable();
        t.string('email', 191).notNullable();
        t.string('phone', 30).nullable();
        t.string('address', 500).nullable();
        t.integer('countryId').unsigned().nullable();
        t.integer('tenantBusinessId').unsigned().nullable();
        t.integer('roleId').unsigned().nullable();
        t.string('password', 255).notNullable();
        t.enum('status', ['active', 'blocked']).notNullable().defaultTo('active');
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.index(['tenantId'], 'idx_tenant_users_tenant_id');
        t.unique(['tenantId', 'email'], 'uq_tenant_users_email');
        t.unique(['tenantId', 'username'], 'uq_tenant_users_username');
      });
      logger.info('Auto-migration: tenant_users table created');
    }
  } catch (err: any) {
    logger.warn('Auto-migration for tenant_users skipped or failed', { error: err.message });
  }
};

// Ensure tenant_lcos table exists (auto-migration for v1.40.0)
const ensureTenantLcosTable = async () => {
  try {
    const exists = await db.schema.hasTable('tenant_lcos');
    if (!exists) {
      await db.schema.createTable('tenant_lcos', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.integer('tenantId').unsigned().notNullable();
        t.integer('tenantBusinessId').unsigned().notNullable();
        t.string('businessName', 100).notNullable();
        t.string('code', 50).notNullable();
        t.string('lcoName', 255).notNullable();
        t.string('phone', 30).notNullable();
        t.string('email', 191).notNullable();
        t.string('address_line1', 255).notNullable();
        t.string('city', 100).notNullable();
        t.string('state', 100).notNullable();
        t.string('pincode', 20).notNullable();
        t.integer('countryId').unsigned().nullable();
        t.enum('status', ['active', 'inactive', 'deleted']).notNullable().defaultTo('active');
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.datetime('deletedAt').nullable();

        t.index(['tenantId'], 'idx_lcos_tenant_id');
        t.index(['tenantBusinessId'], 'idx_lcos_business_id');
        t.unique(['tenantBusinessId', 'code'], 'uq_lcos_business_code');
      });
      logger.info('Auto-migration: tenant_lcos table created');
    }
  } catch (err: any) {
    logger.warn('Auto-migration for tenant_lcos skipped or failed', { error: err.message });
  }
};

// Ensure tenant_upstream_providers table exists (auto-migration for v1.41.0)
const ensureTenantUpstreamProvidersTable = async () => {
  try {
    const exists = await db.schema.hasTable('tenant_upstream_providers');
    if (!exists) {
      await db.schema.createTable('tenant_upstream_providers', (t: any) => {
        t.increments('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.integer('tenantBusinessId').unsigned().notNullable();
        t.string('name', 255).notNullable();
        t.string('code', 20).notNullable();
        t.enum('serviceCategory', ['cabletv', 'bandwidth', 'iptv', 'hybrid']).notNullable();
        t.string('contactPerson', 255).notNullable();
        t.string('phone', 30).notNullable();
        t.string('email', 191).notNullable();
        t.string('addressLine1', 255).notNullable();
        t.string('city', 100).notNullable();
        t.string('state', 100).notNullable();
        t.integer('countryId').unsigned().nullable();
        t.enum('status', ['active', 'inactive', 'blocked', 'deleted']).notNullable().defaultTo('active');
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.datetime('deletedAt').nullable();
        t.index(['tenantBusinessId'], 'idx_upstream_providers_business_id');
        t.index(['status'], 'idx_upstream_providers_status');
        t.unique(['tenantBusinessId', 'code'], 'uq_upstream_providers_business_code');
        t.unique(['tenantBusinessId', 'email'], 'uq_upstream_providers_business_email');
        t.unique(['tenantBusinessId', 'phone'], 'uq_upstream_providers_business_phone');
      });
      logger.info('Auto-migration: tenant_upstream_providers table created');
    }
  } catch (err: any) {
    logger.warn('Auto-migration for tenant_upstream_providers skipped or failed', { error: err.message });
  }
};

// Ensure tenant_cable_types table exists (auto-migration for v1.45.0)
const ensureTenantCableTypesTable = async () => {
  try {
    const exists = await db.schema.hasTable('tenant_cable_types');
    if (!exists) {
      await db.schema.createTable('tenant_cable_types', (t: any) => {
        t.increments('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.integer('tenantBusinessId').unsigned().notNullable();
        t.string('name', 255).notNullable();
        t.string('code', 50).notNullable();
        t.integer('tubeCount').unsigned().notNullable().defaultTo(1);
        t.integer('fiberCoreCount').unsigned().notNullable();
        t.decimal('cableDiameter', 5, 2).notNullable();
        t.text('description').nullable();
        t.enum('status', ['active', 'inactive', 'blocked', 'deleted']).notNullable().defaultTo('active');
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.datetime('deletedAt').nullable();
        t.index(['tenantBusinessId'], 'idx_cable_types_business_id');
        t.index(['status'], 'idx_cable_types_status');
        t.unique(['tenantBusinessId', 'code'], 'uq_cable_types_business_code');
      });
      logger.info('Auto-migration: tenant_cable_types table created');
    } else {
      // Add tubeCount column to existing tables (v1.47.0)
      const hasTubeCount = await db.schema.hasColumn('tenant_cable_types', 'tubeCount');
      if (!hasTubeCount) {
        await db.schema.alterTable('tenant_cable_types', (t: any) => {
          t.integer('tubeCount').unsigned().notNullable().defaultTo(1).after('code');
        });
        logger.info('Auto-migration: added tubeCount column to tenant_cable_types');
      }
    }
  } catch (err: any) {
    logger.warn('Auto-migration for tenant_cable_types skipped or failed', { error: err.message });
  }
};

// Ensure tenant_device_categories table exists (auto-migration for v1.49.0)
const ensureTenantDeviceCategoriesTable = async () => {
  try {
    const exists = await db.schema.hasTable('tenant_device_categories');
    if (!exists) {
      await db.schema.createTable('tenant_device_categories', (t: any) => {
        t.increments('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.integer('tenantBusinessId').unsigned().notNullable();
        t.string('name', 255).notNullable();
        t.string('code', 50).notNullable();
        t.text('description').nullable();
        t.enum('status', ['active', 'inactive', 'deleted']).notNullable().defaultTo('active');
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.datetime('deletedAt').nullable();
        t.index(['tenantBusinessId'], 'idx_device_categories_business_id');
        t.index(['status'], 'idx_device_categories_status');
        t.unique(['tenantBusinessId', 'code'], 'uq_device_categories_business_code');
      });
      logger.info('Auto-migration: tenant_device_categories table created');
    }
  } catch (err: any) {
    logger.warn('Auto-migration for tenant_device_categories skipped or failed', { error: err.message });
  }
};

// Ensure tenant_device_types table exists (auto-migration for v1.50.0)
const ensureTenantDeviceTypesTable = async () => {
  try {
    const exists = await db.schema.hasTable('tenant_device_types');
    if (!exists) {
      await db.schema.createTable('tenant_device_types', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.bigInteger('tenantBusinessId').unsigned().notNullable();
        t.bigInteger('tenantDeviceCategoryId').unsigned().notNullable();
        t.string('name', 100).notNullable();
        t.string('code', 50).notNullable();
        t.boolean('isModelNumberRequired').notNullable().defaultTo(false);
        t.boolean('isSerialNumberRequired').notNullable().defaultTo(false);
        t.boolean('isMacAddressRequired').notNullable().defaultTo(false);
        t.boolean('isIPAddressRequired').notNullable().defaultTo(false);
        t.boolean('isGpsLocationRequired').notNullable().defaultTo(false);
        t.text('description').nullable();
        t.enum('status', ['active', 'inactive', 'deleted']).notNullable().defaultTo('active');
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.datetime('deletedAt').nullable();
        t.index(['tenantBusinessId'], 'idx_device_types_business_id');
        t.index(['tenantDeviceCategoryId'], 'idx_device_types_category_id');
        t.index(['status'], 'idx_device_types_status');
        t.unique(['tenantBusinessId', 'code'], 'uq_device_types_business_code');
      });
      logger.info('Auto-migration: tenant_device_types table created');
    }
  } catch (err: any) {
    logger.warn('Auto-migration for tenant_device_types skipped or failed', { error: err.message });
  }
};

// Ensure tenant_user_settings table exists (auto-migration for v1.51.0)
const ensureTenantUserSettingsTable = async () => {
  try {
    const exists = await db.schema.hasTable('tenant_user_settings');
    if (!exists) {
      await db.schema.createTable('tenant_user_settings', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.bigInteger('tenantBusinessId').unsigned().notNullable();
        t.bigInteger('tenantUserId').unsigned().notNullable();
        t.string('name', 100).notNullable();
        t.string('key', 100).notNullable();
        t.text('value').notNullable();
        t.enum('status', ['active', 'inactive', 'deleted']).notNullable().defaultTo('active');
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.datetime('deletedAt').nullable();
        t.index(['tenantBusinessId', 'tenantUserId'], 'idx_user_settings_user');
        t.unique(['tenantBusinessId', 'tenantUserId', 'key'], 'uq_user_settings_key');
      });
      logger.info('Auto-migration: tenant_user_settings table created');
    }
  } catch (err: any) {
    logger.warn('Auto-migration for tenant_user_settings skipped or failed', { error: err.message });
  }
};

// Ensure tenant_support_tickets tables exist (auto-migration for v1.47.0)
const ensureSupportTicketTables = async () => {
  try {
    const ticketsExists = await db.schema.hasTable('tenant_support_tickets');
    if (!ticketsExists) {
      await db.schema.createTable('tenant_support_tickets', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.integer('tenantId').unsigned().notNullable();
        t.integer('tenantBusinessId').unsigned().notNullable();
        t.string('ticketNumber', 30).notNullable().unique();
        t.string('subject', 255).notNullable();
        t.text('description').notNullable();
        t.enum('category', ['network', 'fiber', 'iptv', 'billing', 'account', 'technical', 'other']).notNullable().defaultTo('other');
        t.enum('priority', ['low', 'medium', 'high', 'critical']).notNullable().defaultTo('medium');
        t.enum('impactLevel', ['low', 'medium', 'high']).notNullable().defaultTo('medium');
        t.enum('status', ['open', 'assigned', 'in_progress', 'on_hold', 'resolved', 'closed', 'reopened']).notNullable().defaultTo('open');
        t.integer('assignedTo').unsigned().nullable();
        t.datetime('assignedAt').nullable();
        t.integer('slaResponseTime').unsigned().nullable();
        t.integer('slaResolutionTime').unsigned().nullable();
        t.datetime('dueAt').nullable();
        t.string('relatedNodeId', 36).nullable();
        t.string('relatedRouteId', 36).nullable();
        t.string('relatedCustomerId', 36).nullable();
        t.json('attachments').nullable();
        t.json('metadata').nullable();
        t.text('resolutionNotes').nullable();
        t.datetime('resolvedAt').nullable();
        t.datetime('closedAt').nullable();
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.datetime('deletedAt').nullable();
        t.index(['tenantId'], 'idx_tickets_tenant_id');
        t.index(['tenantBusinessId'], 'idx_tickets_business_id');
        t.index(['status'], 'idx_tickets_status');
        t.index(['priority'], 'idx_tickets_priority');
        t.index(['assignedTo'], 'idx_tickets_assigned_to');
      });
      logger.info('Auto-migration: tenant_support_tickets table created');
    }

    const messagesExists = await db.schema.hasTable('tenant_ticket_messages');
    if (!messagesExists) {
      await db.schema.createTable('tenant_ticket_messages', (t: any) => {
        t.bigIncrements('id').primary();
        t.integer('ticketId').unsigned().notNullable();
        t.enum('senderType', ['tenant', 'admin', 'system']).notNullable();
        t.integer('senderId').unsigned().notNullable();
        t.text('message').notNullable();
        t.json('attachments').nullable();
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.index(['ticketId'], 'idx_ticket_messages_ticket_id');
      });
      logger.info('Auto-migration: tenant_ticket_messages table created');
    }

    const logsExists = await db.schema.hasTable('tenant_ticket_logs');
    if (!logsExists) {
      await db.schema.createTable('tenant_ticket_logs', (t: any) => {
        t.bigIncrements('id').primary();
        t.integer('ticketId').unsigned().notNullable();
        t.string('action', 100).notNullable();
        t.string('oldValue', 500).nullable();
        t.string('newValue', 500).nullable();
        t.integer('performedBy').unsigned().nullable();
        t.string('performerName', 255).nullable();
        t.datetime('performedAt').notNullable().defaultTo(db.fn.now());
        t.index(['ticketId'], 'idx_ticket_logs_ticket_id');
      });
      logger.info('Auto-migration: tenant_ticket_logs table created');
    } else {
      const hasPerformerName = await db.schema.hasColumn('tenant_ticket_logs', 'performerName');
      if (!hasPerformerName) {
        await db.schema.alterTable('tenant_ticket_logs', (t: any) => {
          t.string('performerName', 255).nullable().after('performedBy');
        });
        logger.info('Auto-migration: tenant_ticket_logs.performerName column added');
      }
    }
  } catch (err: any) {
    logger.warn('Auto-migration for support ticket tables skipped or failed', { error: err.message });
  }
};

// Ensure widgets table exists (auto-migration for v1.56.0)
const ensureWidgetsTable = async () => {
  try {
    const exists = await db.schema.hasTable('widgets');
    if (!exists) {
      await db.schema.createTable('widgets', (t: any) => {
        t.increments('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.string('code', 100).notNullable().unique();
        t.string('name', 255).notNullable();
        t.enum('type', ['active_device', 'passive_device', 'power_device', 'junction', 'fiber_terminal', 'splitter', 'coupler']).notNullable();
        t.enum('iconType', ['svg', 'png', 'webp']).notNullable().defaultTo('svg');
        t.specificType('svgTemplate', 'LONGTEXT').nullable();
        t.string('iconUrl', 512).nullable();
        t.integer('width').unsigned().notNullable().defaultTo(48);
        t.integer('height').unsigned().notNullable().defaultTo(48);
        t.enum('status', ['active', 'inactive', 'deleted']).notNullable().defaultTo('active');
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.datetime('deletedAt').nullable();
        t.index(['type'],   'idx_widgets_type');
        t.index(['status'], 'idx_widgets_status');
      });
      logger.info('Auto-migration: widgets table created');
    }
  } catch (err: any) {
    logger.warn('Auto-migration for widgets table skipped or failed', { error: err.message });
  }
};

// Ensure tenant_routes, tenant_route_points, tenant_route_histories tables exist (v1.57.0)
const ensureTenantRouteTables = async () => {
  try {
    const routesExists = await db.schema.hasTable('tenant_routes');
    if (!routesExists) {
      await db.schema.createTable('tenant_routes', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.bigInteger('tenantBusinessId').unsigned().notNullable();
        t.string('name', 150).notNullable();
        t.string('code', 50).notNullable();
        t.enum('type', ['fiber_route', 'coaxial_route', 'backbone_route', 'distribution_route', 'drop_route', 'underground_duct', 'pole_to_pole']).notNullable();
        t.string('routeColor', 20).nullable();
        t.integer('lineThickness').nullable();
        t.bigInteger('parentRouteId').unsigned().nullable();
        t.text('description').nullable();
        t.enum('status', ['active', 'inactive', 'maintenance', 'deleted']).notNullable().defaultTo('active');
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.datetime('deletedAt').nullable();
        t.unique(['tenantBusinessId', 'code'], 'uq_tenant_routes_business_code');
        t.index(['tenantBusinessId'], 'idx_tenant_routes_business_id');
        t.index(['type'],             'idx_tenant_routes_type');
        t.index(['status'],           'idx_tenant_routes_status');
        t.index(['parentRouteId'],    'idx_tenant_routes_parent_id');
      });
      logger.info('Auto-migration: tenant_routes table created');
    } else {
      // Patch existing table — add columns added after initial release
      const hasDescription = await db.schema.hasColumn('tenant_routes', 'description');
      if (!hasDescription) {
        await db.schema.alterTable('tenant_routes', (t: any) => {
          t.text('description').nullable().after('parentRouteId');
        });
        logger.info('Auto-migration: added description column to tenant_routes');
      }
    }

    const pointsExists = await db.schema.hasTable('tenant_route_points');
    if (!pointsExists) {
      await db.schema.createTable('tenant_route_points', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.bigInteger('tenantRouteId').unsigned().notNullable();
        t.integer('sequenceNumber').notNullable().defaultTo(0);
        t.decimal('latitude',  10, 8).notNullable();
        t.decimal('longitude', 11, 8).notNullable();
        t.decimal('altitude',  10, 2).nullable();
        t.enum('pointType', ['start', 'middle', 'end', 'junction', 'pole', 'device']).notNullable().defaultTo('middle');
        t.string('pointIcon', 36).nullable();
        t.string('deviceTypeUuid', 36).nullable();
        t.string('pointName', 100).nullable();
        t.text('pointDescription').nullable();
        t.text('remarks').nullable();
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.index(['tenantRouteId'],  'idx_route_points_route_id');
        t.index(['sequenceNumber'], 'idx_route_points_seq');
      });
      logger.info('Auto-migration: tenant_route_points table created');
    } else {
      // Patch: drop poleNumber if it still exists
      const hasPoleNumber = await db.schema.hasColumn('tenant_route_points', 'poleNumber');
      if (hasPoleNumber) {
        await db.schema.alterTable('tenant_route_points', (t: any) => { t.dropColumn('poleNumber'); });
        logger.info('Auto-migration: dropped poleNumber column from tenant_route_points');
      }

      // Patch: rename widgetUuid → pointIcon, or add pointIcon if neither exists
      const hasWidgetUuid = await db.schema.hasColumn('tenant_route_points', 'widgetUuid');
      const hasPointIcon  = await db.schema.hasColumn('tenant_route_points', 'pointIcon');
      if (hasWidgetUuid && !hasPointIcon) {
        await db.raw('ALTER TABLE `tenant_route_points` CHANGE COLUMN `widgetUuid` `pointIcon` VARCHAR(36) NULL');
        logger.info('Auto-migration: renamed widgetUuid → pointIcon in tenant_route_points');
      } else if (!hasWidgetUuid && !hasPointIcon) {
        await db.schema.alterTable('tenant_route_points', (t: any) => {
          t.string('pointIcon', 36).nullable().after('pointType');
        });
        logger.info('Auto-migration: added pointIcon column to tenant_route_points');
      }

      // Patch: add deviceTypeUuid column
      const hasDeviceTypeUuid = await db.schema.hasColumn('tenant_route_points', 'deviceTypeUuid');
      if (!hasDeviceTypeUuid) {
        await db.schema.alterTable('tenant_route_points', (t: any) => {
          t.string('deviceTypeUuid', 36).nullable().after('pointIcon');
        });
        logger.info('Auto-migration: added deviceTypeUuid column to tenant_route_points');
      }

      // Patch: add pointName and pointDescription columns
      const hasPointName = await db.schema.hasColumn('tenant_route_points', 'pointName');
      if (!hasPointName) {
        await db.schema.alterTable('tenant_route_points', (t: any) => {
          t.string('pointName', 100).nullable().after('deviceTypeUuid');
          t.text('pointDescription').nullable().after('pointName');
        });
        logger.info('Auto-migration: added pointName and pointDescription columns to tenant_route_points');
      }
    }

    const histExists = await db.schema.hasTable('tenant_route_histories');
    if (!histExists) {
      await db.schema.createTable('tenant_route_histories', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.bigInteger('tenantRouteId').unsigned().notNullable();
        t.enum('actionType', ['created', 'updated', 'deleted', 'restored', 'point_added', 'point_updated', 'point_deleted', 'split', 'merged']).notNullable();
        t.bigInteger('changedByUserId').unsigned().nullable();
        t.json('oldData').nullable();
        t.json('newData').nullable();
        t.string('ipAddress', 45).nullable();
        t.text('userAgent').nullable();
        t.text('remarks').nullable();
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.index(['tenantRouteId'], 'idx_route_hist_route_id');
        t.index(['actionType'],    'idx_route_hist_action');
        t.index(['createdAt'],     'idx_route_hist_created');
      });
      logger.info('Auto-migration: tenant_route_histories table created');
    }

    // Seed permissions
    const hasPermissions = await db.schema.hasTable('permissions');
    if (hasPermissions && routesExists === false) {
      const { generateUuidV7 } = await import('./utils/uuid.js');
      const { nowDb } = await import('./utils/time.js');
      const now = nowDb();
      for (const action of ['view', 'create', 'update', 'delete']) {
        const slug = `tenant_routes.${action}`;
        const existing = await db('permissions').where('slug', slug).first();
        if (!existing) {
          await db('permissions').insert({
            uuid: generateUuidV7(),
            name: `${action.charAt(0).toUpperCase() + action.slice(1)} Tenant Routes`,
            slug,
            resource: 'tenant_routes',
            description: `Can ${action} tenant routes`,
            createdAt: now,
            updatedAt: now,
          });
          logger.info(`Auto-migration: seeded permission '${slug}'`);
        }
      }
      const superAdminRole = await db('roles').where('slug', 'super-admin').select('id').first();
      if (superAdminRole) {
        const newPerms = await db('permissions')
          .whereIn('slug', ['tenant_routes.view', 'tenant_routes.create', 'tenant_routes.update', 'tenant_routes.delete'])
          .select('id');
        for (const perm of newPerms) {
          await db.raw('INSERT IGNORE INTO role_permissions (roleId, permissionId) VALUES (?, ?)', [superAdminRole.id, perm.id]);
        }
        logger.info('Auto-migration: tenant_routes permissions assigned to Super Admin role');
      }
    }
  } catch (err: any) {
    logger.warn('Auto-migration for tenant_route tables skipped or failed', { error: err.message });
  }
};

// Start server
const startServer = async () => {
  try {
    // Verify database connection on startup
    await db.raw('SELECT 1');
    logger.info('Database connection established successfully');

    // Ensure audit_logs table exists (handles existing installs that predate v1.29.0)
    await ensureAuditLogsTable();

    // Ensure tenant_sessions table exists (handles existing installs using tenant_refresh_tokens)
    await ensureTenantSessionsTable();

    // Ensure tenant_users table exists (v1.39.0)
    await ensureTenantUsersTable();

    // Ensure tenant_lcos table exists (v1.40.0)
    await ensureTenantLcosTable();

    // Ensure tenant_upstream_providers table exists (v1.41.0)
    await ensureTenantUpstreamProvidersTable();

    // Ensure tenant_cable_types table exists (v1.45.0)
    await ensureTenantCableTypesTable();

    // Ensure tenant_device_categories table exists (v1.49.0)
    await ensureTenantDeviceCategoriesTable();

    // Ensure tenant_device_types table exists (v1.50.0)
    await ensureTenantDeviceTypesTable();

    // Ensure tenant_user_settings table exists (v1.51.0)
    await ensureTenantUserSettingsTable();

    // Ensure support ticket tables exist (v1.47.0)
    await ensureSupportTicketTables();

    // Ensure widgets table exists (v1.56.0)
    await ensureWidgetsTable();

    // Ensure tenant_route tables exist (v1.57.0)
    await ensureTenantRouteTables();

    // Patch: add route_point to widgets.type enum (v1.59.0)
    try {
      await db.raw(`
        ALTER TABLE widgets
        MODIFY COLUMN type ENUM(
          'active_device','passive_device','power_device',
          'junction','fiber_terminal','splitter','coupler','route_point'
        ) NOT NULL
      `);
      logger.info('Auto-migration: widgets.type enum updated with route_point');
    } catch (err: any) {
      logger.warn('Auto-migration for widgets.type enum skipped or failed', { error: err.message });
    }

    // Patch: add widgetUuid column to tenant_device_types (v1.59.0)
    try {
      const hasWidgetUuid = await db.schema.hasColumn('tenant_device_types', 'widgetUuid');
      if (!hasWidgetUuid) {
        await db.schema.alterTable('tenant_device_types', (t: any) => {
          t.string('widgetUuid', 36).nullable().after('isGpsLocationRequired');
        });
        logger.info('Auto-migration: added widgetUuid column to tenant_device_types');
      }
    } catch (err: any) {
      logger.warn('Auto-migration for tenant_device_types.widgetUuid skipped or failed', { error: err.message });
    }
  } catch (error: any) {
    logger.error('Initial database connection failed. Server is starting but database-dependent routes will return connectivity errors.', {
      error: error.message,
      code: error.code
    });
  }

  app.listen(port, () => {
    logger.info(`Server is running on port ${port}`);
  });
};

startServer();

