import 'dotenv/config';

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Auto-create .env if it doesn't exist so dotenv picks it up on next start
// and setup wizard has a writable target from day one.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.resolve(__dirname, '../.env');
if (!fs.existsSync(envPath)) {
  fs.writeFileSync(envPath, '# Fiber Route Map — generated by first-run\nSETUP_COMPLETE=false\n', 'utf-8');
}

import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { errorHandler } from './middleware/errorHandler.js';
import { versionCheck } from './middleware/versionCheck.js';
import { requestId } from './middleware/requestId.js';
import { dbCheck } from './middleware/dbCheck.js';
import { auth } from './middleware/auth.js';
import userRoutes from './routes/userRoutes.js';
import countryRoutes from './routes/countryRoutes.js';
import roleRoutes from './routes/roleRoutes.js';
import permissionRoutes from './routes/permissionRoutes.js';
import healthRoutes from './routes/healthRoutes.js';
import { authRoutes } from './routes/authRoutes.js';
import setupRoutes from './routes/setupRoutes.js';
import tenantRoutes from './routes/tenantRoutes.js';
import tenantBusinessRoutes from './routes/tenantBusinessRoutes.js';
import tenantUserRoutes from './routes/tenantUserRoutes.js';
import auditLogRoutes, { auditLogService } from './routes/auditLogRoutes.js';
import { auditLog } from './middleware/auditLog.js';
import logger from './utils/logger.js';
import db from './config/database.js';
import swaggerUi from 'swagger-ui-express';
import { swaggerSpec } from './docs/swaggerConfig.js';
import { AuthRepository } from './repositories/AuthRepository.js';
import { UserRepository } from './repositories/UserRepository.js';
import { TenantRepository } from './repositories/TenantRepository.js';
import { AuthService } from './services/AuthService.js';

const app = express();
const port = process.env.PORT || 3001;

// Initialize repositories and services
const authRepo = new AuthRepository();
const userRepo = new UserRepository();
const tenantRepo = new TenantRepository();
const authService = new AuthService(authRepo, userRepo, tenantRepo);

// Use extended query parser (qs) to support nested bracket notation like filter[status]=active
app.set('query parser', 'extended');

// Middleware
app.use(helmet());
app.use(cors({
  origin: '*', // For development, adjust for production
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH'],
  allowedHeaders: ['Content-Type', 'Authorization', 'X-API-Version', 'X-Mgmt-Token', 'X-Device-Id', 'X-Device-Name'],
  exposedHeaders: ['Content-Type', 'Authorization']
}));
app.use(express.json());
app.use(requestId);

// Setup routes — BEFORE versionCheck/dbCheck/auth so they work before DB exists
app.use('/api/setup', setupRoutes);

app.use(versionCheck);
app.use(dbCheck);

// Audit log middleware — runs on all API routes (after auth is available per-route)
app.use('/api', auditLog(auditLogService));

// Routes
app.use('/api/auth', authRoutes(authService));
app.use('/api/users', auth(authService), userRoutes);
app.use('/api/countries', auth(authService), countryRoutes);
app.use('/api/roles', auth(authService), roleRoutes);
app.use('/api/permissions', permissionRoutes);
app.use('/api/tenants', auth(authService), tenantRoutes);
app.use('/api/tenant-business', auth(authService), tenantBusinessRoutes);
app.use('/api/tenant/users', tenantUserRoutes);
app.use('/api/audit-logs', auth(authService), auditLogRoutes);
app.use('/api/health', healthRoutes);
app.get('/api/docs/spec', (_req: express.Request, res: express.Response) => res.json(swaggerSpec));
app.use('/api/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));

// Root route
app.get('/', (req: express.Request, res: express.Response) => {
  res.json({ message: 'Fiber Route Map Node.js API' });
});

/*
// Catch-all for undefined /api routes
app.all('/api/:path*', (req: express.Request, res: express.Response) => {
  res.status(200).json({
    success: false,
    statusCode: 404,
    errorType: 'NOT_FOUND',
    message: `Route ${req.method} ${req.url} not found`,
    help: 'Please verify the API endpoint and HTTP method.'
  });
});
*/

// Error handling
app.use(errorHandler);

// Ensure audit_logs table exists (auto-migration for existing installs)
const ensureAuditLogsTable = async () => {
  try {
    const exists = await db.schema.hasTable('audit_logs');
    if (!exists) {
      await db.schema.createTable('audit_logs', (t) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.enum('actorType', ['user', 'system', 'anonymous']).notNullable().defaultTo('anonymous');
        t.string('actorUuid', 36).nullable();
        t.string('actorName', 255).nullable();
        t.string('actorEmail', 191).nullable();
        t.json('actorRoles').nullable();
        t.string('action', 100).notNullable();
        t.string('resource', 100).notNullable();
        t.string('resourceUuid', 36).nullable();
        t.string('resourceName', 255).nullable();
        t.string('httpMethod', 10).notNullable();
        t.string('endpoint', 500).notNullable();
        t.smallint('statusCode').unsigned().notNullable();
        t.boolean('success').notNullable().defaultTo(true);
        t.json('requestBody').nullable();
        t.json('responseBody').nullable();
        t.string('ipAddress', 45).nullable();
        t.text('userAgent').nullable();
        t.string('requestId', 100).nullable();
        t.string('sessionUuid', 36).nullable();
        t.integer('durationMs').unsigned().notNullable().defaultTo(0);
        t.text('errorMessage').nullable();
        t.timestamp('createdAt').notNullable().defaultTo(db.fn.now());
        t.index(['actorUuid'], 'idx_audit_actor_uuid');
        t.index(['action'], 'idx_audit_action');
        t.index(['resource'], 'idx_audit_resource');
        t.index(['createdAt'], 'idx_audit_created');
        t.index(['statusCode'], 'idx_audit_status_code');
        t.index(['ipAddress'], 'idx_audit_ip');
        t.index(['requestId'], 'idx_audit_request_id');
      });
      logger.info('Auto-migration: audit_logs table created');

      // Seed audit_log permissions if the permissions table exists
      const hasPermissions = await db.schema.hasTable('permissions');
      if (hasPermissions) {
        const { generateUuidV7 } = await import('./utils/uuid.js');
        const { nowDb } = await import('./utils/time.js');
        const now = nowDb();
        for (const action of ['view', 'export']) {
          const slug = `audit_log.${action}`;
          const existing = await db('permissions').where('slug', slug).first();
          if (!existing) {
            await db('permissions').insert({
              uuid: generateUuidV7(),
              name: `${action.charAt(0).toUpperCase() + action.slice(1)} Audit Logs`,
              slug,
              resource: 'audit_log',
              description: `Can ${action} audit logs`,
              createdAt: now,
              updatedAt: now,
            });
            logger.info(`Auto-migration: seeded permission '${slug}'`);
          }
        }

        // Assign new permissions to Super Admin role if it exists
        const superAdminRole = await db('roles').where('slug', 'super-admin').select('id').first();
        if (superAdminRole) {
          const newPerms = await db('permissions')
            .whereIn('slug', ['audit_log.view', 'audit_log.export'])
            .select('id');
          for (const perm of newPerms) {
            await db.raw(
              'INSERT IGNORE INTO role_permissions (roleId, permissionId) VALUES (?, ?)',
              [superAdminRole.id, perm.id]
            );
          }
          logger.info('Auto-migration: audit_log permissions assigned to Super Admin role');
        }
      }
    }
  } catch (err: any) {
    logger.warn('Auto-migration for audit_logs skipped or failed', { error: err.message });
  }
};

// Ensure tenant_sessions table exists (auto-migration for existing installs using tenant_refresh_tokens)
const ensureTenantSessionsTable = async () => {
  try {
    const exists = await db.schema.hasTable('tenant_sessions');
    if (!exists) {
      await db.schema.createTable('tenant_sessions', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.integer('tenantId').unsigned().notNullable();
        t.string('sessionToken', 500).notNullable().unique();
        t.string('deviceId', 255).nullable();
        t.string('deviceName', 255).nullable();
        t.string('ipAddress', 45).nullable();
        t.text('userAgent').nullable();
        t.datetime('expiresAt').notNullable();
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.index(['tenantId'], 'idx_tenant_sessions_tenant_id');
        t.index(['expiresAt'], 'idx_tenant_sessions_expires_at');
      });
      logger.info('Auto-migration: tenant_sessions table created');
    }
  } catch (err: any) {
    logger.warn('Auto-migration for tenant_sessions skipped or failed', { error: err.message });
  }
};

// Ensure tenant_users table exists (auto-migration for v1.39.0)
const ensureTenantUsersTable = async () => {
  try {
    const exists = await db.schema.hasTable('tenant_users');
    if (!exists) {
      await db.schema.createTable('tenant_users', (t: any) => {
        t.bigIncrements('id').primary();
        t.string('uuid', 36).notNullable().unique();
        t.integer('tenantId').unsigned().notNullable();
        t.string('name', 255).notNullable();
        t.string('username', 100).notNullable();
        t.string('email', 191).notNullable();
        t.string('phone', 30).nullable();
        t.string('address', 500).nullable();
        t.integer('countryId').unsigned().nullable();
        t.integer('tenantBusinessId').unsigned().nullable();
        t.integer('roleId').unsigned().nullable();
        t.string('password', 255).notNullable();
        t.enum('status', ['active', 'blocked']).notNullable().defaultTo('active');
        t.datetime('createdAt').notNullable().defaultTo(db.fn.now());
        t.datetime('updatedAt').notNullable().defaultTo(db.fn.now());
        t.index(['tenantId'], 'idx_tenant_users_tenant_id');
        t.unique(['tenantId', 'email'], 'uq_tenant_users_email');
        t.unique(['tenantId', 'username'], 'uq_tenant_users_username');
      });
      logger.info('Auto-migration: tenant_users table created');
    }
  } catch (err: any) {
    logger.warn('Auto-migration for tenant_users skipped or failed', { error: err.message });
  }
};

// Start server
const startServer = async () => {
  try {
    // Verify database connection on startup
    await db.raw('SELECT 1');
    logger.info('Database connection established successfully');

    // Ensure audit_logs table exists (handles existing installs that predate v1.29.0)
    await ensureAuditLogsTable();

    // Ensure tenant_sessions table exists (handles existing installs using tenant_refresh_tokens)
    await ensureTenantSessionsTable();

    // Ensure tenant_users table exists (v1.39.0)
    await ensureTenantUsersTable();
  } catch (error: any) {
    logger.error('Initial database connection failed. Server is starting but database-dependent routes will return connectivity errors.', {
      error: error.message,
      code: error.code
    });
  }

  app.listen(port, () => {
    logger.info(`Server is running on port ${port}`);
  });
};

startServer();

